// Generated by CoffeeScript 1.6.2
(function() {
  var App;

  App = Ember.Application.create();

  App.Router.map(function() {
    this.resource('about');
    this.resource('vmguests', function() {
      return this.resource('vmguest', {
        path: '/:vmguest_name'
      });
    });
    this.resource('configitems', function() {
      return this.resource('configitem', {
        path: '/:configitem_name'
      });
    });
    return this.resource('hsns', function() {
      return this.resource('hsn', {
        path: '/:hsn_name'
      });
    });
  });

  App.HsnsRoute = Ember.Route.extend({
    model: function() {
      var hsns;

      return hsns = App.Hsn.all();
    }
  });

  App.HsnRoute = Ember.Route.extend({
    model: function(params) {
      var hsn;

      return hsn = App.Hsn.find(params.hsn_name);
    },
    serialize: function(model) {
      return {
        hsn_name: model.name.replace(new RegExp(" ", "g"), "_")
      };
    }
  });

  App.ConfigitemsRoute = Ember.Route.extend({
    model: function() {
      var configItems;

      return configItems = App.Configitem.all();
    }
  });

  App.ConfigitemRoute = Ember.Route.extend({
    model: function(params) {
      var configItem;

      return configItem = App.Configitem.find(params.configitem_name);
    },
    serialize: function(model) {
      return {
        configitem_name: model.full_node_name
      };
    }
  });

  App.VmguestsRoute = Ember.Route.extend({
    model: function() {
      var vms;

      return vms = App.Vmguest.all();
    }
  });

  App.VmguestRoute = Ember.Route.extend({
    model: function(params) {
      var vm;

      vm = App.Vmguest.find(params.vmguest_name);
      return vm;
    },
    serialize: function(model) {
      return {
        vmguest_name: model.full_node_name
      };
    }
  });

  App.Vmguest = Ember.Object.extend({
    full_node_name: ""
  });

  App.Vmguest.reopenClass({
    all: function() {
      var json_url, vms;

      json_url = "http://localhost:7474/db/data/label/vmwareGuest/nodes";
      vms = [];
      return $.getJSON(json_url).then((function(response) {
        response.forEach(function(item) {
          return vms.push(App.Vmguest.create(item.data));
        });
        return vms;
      }));
    },
    find: function(name) {
      var json_url;

      console.log(name);
      json_url = "http://localhost:7474/db/data/label/vmwareGuest/nodes?full_node_name=%22" + name + "%22";
      console.log(json_url);
      return $.getJSON(json_url).then((function(response) {
        var vm;

        console.log('in Vmguest find');
        console.log('json: ' + response);
        $.each(response, function(i, item) {
          return console.log(item['data']);
        });
        console.log(response[0]['data']['full_node_name']);
        vm = App.Vmguest.create(response[0]['data']);
        return vm;
      }));
    }
  });

  App.Configitem = Ember.Object.extend({
    full_node_name: ""
  });

  App.Configitem.reopenClass({
    all: function() {
      var cis, json_url;

      json_url = "http://localhost:7474/db/data/label/ci/nodes";
      cis = [];
      return $.getJSON(json_url).then((function(response) {
        response.forEach(function(item) {
          return cis.push(App.Configitem.create(item.data));
        });
        return cis;
      }));
    },
    find: function(name) {
      var json_url;

      json_url = "http://localhost:7474/db/data/label/ci/nodes?full_node_name=%22" + name + "%22";
      return $.getJSON(json_url).then((function(response) {
        var vm;

        vm = App.Configitem.create(response[0]['data']);
        return vm;
      }));
    }
  });

  App.Hsn = Ember.Object.extend({
    name: ""
  });

  App.Hsn.reopenClass({
    all: function() {
      var hsns, json_url;

      json_url = "http://localhost:7474/db/data/label/hsn/nodes";
      hsns = [];
      return $.getJSON(json_url).then((function(response) {
        response.forEach(function(item) {
          return hsns.push(App.Hsn.create(item.data));
        });
        return hsns;
      }));
    },
    find: function(name) {
      var json_data, json_url;

      name.replace(new RegExp("_", "g"), " ");
      console.log("In hsn find: " + name);
      json_data = {
        query: "MATCH n:hsn<-[:IS_COMPONENT_OF]-m:ci WHERE n.name! = 'vio prd hpg' RETURN m"
      };
      console.log(json_data);
      json_url = "http://localhost:7474/db/data/cypher";
      return $.post(json_url, json_data).then(function(response) {
        console.log(response["data"][0]["data"]);
        return response;
      });
    }
  });

}).call(this);
